export const Routes = {
  ADD_SKILL: "addSkill",
  ADD_TASK: "addTask",
  COMPLETE_TASK: "completeTask",
  DELETE_FILE: "deleteFile",
  DELETE_SKILL: "deleteSkill/:skillId",
  DELETE_TASK: "tasks/:taskId",
  GET_SKILLS: "getSkills",
  LOGIN: "login",
  LOGOUT: "logout",
  REFRESH: "refresh",
  REPLACE_FILE: "replaceFile",
  SINGLE_SKILL: "singleSkill/:skillId",
  SKILL: "skill",
  TASKS: "tasks",
  UPDATE_SKILL: "updateSkill/:skillId",
  UPDATE_TASK: "updateTask/:taskId",
  UPDATE_USER: "updateUser",
  UPLOAD: "upload",
  USER: "user",
  USERS: "users",
};
