export const Routes = {
  DELETE_FILE: "deleteFile",
  LOGIN: "login",
  LOGOUT: "logout",
  REFRESH: "refresh",
  REPLACE_FILE: "replaceFile",
  UPDATE_USER: "updateUser",
  UPLOAD: "upload",
  USER: "user",
  USERS: "users",
  ADD_SKILL: "addSkill",
  GET_SKILLS: "getSkills",
  SKILL: "skill",
  ADD_TASK: "addTask",
  TASKS: "tasks",
  UPDATE_TASK: "updateTask/:taskId",
  DELETE_TASK: "tasks/:taskId",
};
